name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }} ${{ matrix.cuda }}
    strategy:
      matrix:
        include:
          - name: deepmd-kit-cpu
          - name: deepmd-kit-gpu
            cuda: '11.1'
          - name: deepmd-kit-gpu
            cuda: '11.0'
          - name: deepmd-kit-gpu
            cuda: '10.1'
          - name: deepmd-kit-gpu
            cuda: '10.0'
          - name: deepmd-kit-gpu
            cuda: '9.2'
    steps:
    - uses: actions/checkout@master
    - uses: s-weigand/setup-conda@v1
    - run: conda install constructor jinja2 -y
    - run: constructor ${{ matrix.name }}
      env:
        VERSION: 2.0.0.b1
        CUDA_VERSION: ${{ matrix.cuda }}
    - run: split -a 1 -d -n 2 deepmd-kit-*.sh deepmd-kit-*.sh. && rm deepmd-kit-*.sh
      if: matrix.cuda == '11.0' || matrix.cuda == '11.1'
    - name: Upload to release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to release 2
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
        tag_name: v2.0.0.b1 
        repository: deepmodeling/deepmd-kit
        prerelease: true
        name: v2.0.0-beta.1
      env:
        GITHUB_TOKEN: ${{ secrets.DEEPMD_GITHUB_TOKEN }}
