name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }} ${{ matrix.cuda }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: deepmd-kit
            platform: linux-64
          - name: deepmd-kit
            cuda: '11.8'
            platform: linux-64
          #- name: deepmd-kit-gpu
          #  cuda: '10.2'
          #  platform: linux-ppc64le
    env:
      version: "2.2.7"
    steps:
    - uses: actions/checkout@v4
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: "3.11"
    - run: conda install constructor jinja2 conda-libmamba-solver -y
    #- run: wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-${{ matrix.platform }}.exe -O conda.exe
    - run: constructor ${{ matrix.name }} --platform ${{ matrix.platform }} #--conda-exe ./conda.exe
      env:
        CONDA_SOLVER: libmamba
        VERSION: ${{ env.version }}
        CUDA_VERSION: ${{ matrix.cuda }}
        CONDA_OVERRIDE_CUDA: ${{ matrix.cuda }}
    - run: export NAME=`ls deepmd-kit-*.sh` && split -a 1 -d -n 2 ${NAME} ${NAME}. && rm deepmd-kit-*.sh
      if: matrix.cuda == '11.8'
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to release 2
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
        tag_name: v${{ env.version }}
        repository: deepmodeling/deepmd-kit
        prerelease: false
        name: v2.2.7
        append_body: true
      env:
        GITHUB_TOKEN: ${{ secrets.DEEPMD_GITHUB_TOKEN }}
