name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }} ${{ matrix.cuda }}
    strategy:
      matrix:
        include:
          - name: deepmd-kit-cpu
          - name: deepmd-kit-gpu
            cuda: '11.3'
          - name: deepmd-kit-gpu
            cuda: '10.1'
    steps:
    - uses: actions/checkout@master
    - uses: s-weigand/setup-conda@v1
    - run: conda install constructor jinja2 -y
    - run: constructor ${{ matrix.name }}
      env:
        VERSION: 2.0.0.b4
        CUDA_VERSION: ${{ matrix.cuda }}
    - run: export NAME=`ls deepmd-kit-*.sh` && split -a 1 -d -n 2 ${NAME} ${NAME}. && rm deepmd-kit-*.sh
      if: matrix.cuda == '11.3'
    - name: Upload to release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to release 2
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deepmd-kit-*.sh*
        tag_name: v2.0.0.b4
        repository: deepmodeling/deepmd-kit
        prerelease: true
        name: v2.0.0-beta.4
      env:
        GITHUB_TOKEN: ${{ secrets.DEEPMD_GITHUB_TOKEN }}
